server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: personaltracker-main

database:
  uri: "mongodb+srv://tomator5000:3C9aHZ5GQAFOYBVa@cluster0.jpsbr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"